services:
  postgres:
    image: postgres:16
    container_name: terraherb-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: terraherb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: terraherb-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
